CREATE DATABASE IF NOT EXISTS dbs13101396;
USE dbs13101396;

CREATE TABLE users (
	account VARCHAR(50) NOT NULL UNIQUE,
	signature VARCHAR(150),
	grade_level TINYINT UNSIGNED DEFAULT 5,
	accountCreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	lastLogin DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	numberOfTestsTaken INT UNSIGNED DEFAULT 0,
	credits INT UNSIGNED DEFAULT 0,
	expPoints INT UNSIGNED DEFAULT 0,
	goldCoins INT UNSIGNED DEFAULT 0,
	PRIMARY KEY (account)
);
